export const categories = [
  "Web Development",
  "Mobile Development",
  "Data Science",
  "AI / ML",
  "Cyber Security",
  "DevOps",
  "Cloud Computing",
  "Blockchain",
  "UI/UX Design",
  "Game Development",
  "Programming Languages",
  "Software Testing",
  "Digital Marketing",
  "Business",
  "Finance",
  "Photography",
  "Music",
  "Fitness",
  "Other",
];
